<?php

namespace ContainerImxEj8r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dus8DjxService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.dus8Djx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dus8Djx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'providerRepository' => ['privates', 'App\\Repository\\ProviderRepository', 'getProviderRepositoryService', true],
        ], [
            'providerRepository' => 'App\\Repository\\ProviderRepository',
        ]);
    }
}
