<?php

namespace ContainerImxEj8r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.X9jceM4.App\Entity\Provider' shared service.
     *
     * @return \App\Entity\Provider
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.X9jceM4": it references class "App\\Entity\\Provider" but no such service exists.');
    }
}
