<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'flux' => [[], ['_controller' => 'App\\Controller\\FluxController::index'], [], [['text', '/flux']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'data_management' => [[], ['_controller' => 'App\\Controller\\HomeController::data_management'], [], [['text', '/data_management']], [], []],
    'label_index' => [[], ['_controller' => 'App\\Controller\\LabelController::index'], [], [['text', '/label']], [], []],
    'generate_word' => [[], ['_controller' => 'App\\Controller\\LabelController::generateWordFile'], [], [['text', '/label/generateWord']], [], []],
    'download_label' => [[], ['_controller' => 'App\\Controller\\LabelController::downloadLabels'], [], [['text', '/label/download']], [], []],
    'product_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/']], [], []],
    'product_es' => [[], ['_controller' => 'App\\Controller\\ProductController::es'], [], [['text', '/product/entries_exits']], [], []],
    'product_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new']], [], []],
    'product_search' => [[], ['_controller' => 'App\\Controller\\ProductController::searchByBarcode'], [], [['text', '/product/search']], [], []],
    'generate_barcode' => [[], ['_controller' => 'App\\Controller\\ProductController::generateBarcode'], [], [['text', '/product/generate_barcode']], [], []],
    'product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'provider_index' => [[], ['_controller' => 'App\\Controller\\ProviderController::index'], [], [['text', '/provider/']], [], []],
    'provider_new' => [[], ['_controller' => 'App\\Controller\\ProviderController::new'], [], [['text', '/provider/new']], [], []],
    'provider_show' => [['id'], ['_controller' => 'App\\Controller\\ProviderController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/provider']], [], []],
    'provider_edit' => [['id'], ['_controller' => 'App\\Controller\\ProviderController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/provider']], [], []],
    'provider_delete' => [['id'], ['_controller' => 'App\\Controller\\ProviderController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/provider']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], []],
    'user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/new']], [], []],
    'user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
];
