<?php

namespace Container46kqArj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZSG7vMUService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZSG7vMU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZSG7vMU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fluxRepository' => ['privates', 'App\\Repository\\FluxRepository', 'getFluxRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'fluxRepository' => 'App\\Repository\\FluxRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
