<?php

namespace Container46kqArj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WELIojuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.WELIoju' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WELIoju'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ean13Generator' => ['privates', 'App\\Service\\Ean13Generator', 'getEan13GeneratorService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'ean13Generator' => 'App\\Service\\Ean13Generator',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
