<?php

namespace Container46kqArj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FluxController::index' => ['privates', '.service_locator.ZSG7vMU', 'get_ServiceLocator_ZSG7vMUService', true],
            'App\\Controller\\LabelController::generateWordFile' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\LabelController::index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductController::es' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::generateBarcode' => ['privates', '.service_locator.WELIoju', 'get_ServiceLocator_WELIojuService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.J7N_mTY', 'get_ServiceLocator_J7NMTYService', true],
            'App\\Controller\\ProductController::searchByBarcode' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProviderController::delete' => ['privates', '.service_locator.X9jceM4', 'get_ServiceLocator_X9jceM4Service', true],
            'App\\Controller\\ProviderController::edit' => ['privates', '.service_locator.X9jceM4', 'get_ServiceLocator_X9jceM4Service', true],
            'App\\Controller\\ProviderController::index' => ['privates', '.service_locator.dus8Djx', 'get_ServiceLocator_Dus8DjxService', true],
            'App\\Controller\\ProviderController::show' => ['privates', '.service_locator.X9jceM4', 'get_ServiceLocator_X9jceM4Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.8dS8kbD', 'get_ServiceLocator_8dS8kbDService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Aqud7U5', 'get_ServiceLocator_Aqud7U5Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\FluxController:index' => ['privates', '.service_locator.ZSG7vMU', 'get_ServiceLocator_ZSG7vMUService', true],
            'App\\Controller\\LabelController:generateWordFile' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\LabelController:index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductController:es' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:generateBarcode' => ['privates', '.service_locator.WELIoju', 'get_ServiceLocator_WELIojuService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.J7N_mTY', 'get_ServiceLocator_J7NMTYService', true],
            'App\\Controller\\ProductController:searchByBarcode' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProviderController:delete' => ['privates', '.service_locator.X9jceM4', 'get_ServiceLocator_X9jceM4Service', true],
            'App\\Controller\\ProviderController:edit' => ['privates', '.service_locator.X9jceM4', 'get_ServiceLocator_X9jceM4Service', true],
            'App\\Controller\\ProviderController:index' => ['privates', '.service_locator.dus8Djx', 'get_ServiceLocator_Dus8DjxService', true],
            'App\\Controller\\ProviderController:show' => ['privates', '.service_locator.X9jceM4', 'get_ServiceLocator_X9jceM4Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.8dS8kbD', 'get_ServiceLocator_8dS8kbDService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Aqud7U5', 'get_ServiceLocator_Aqud7U5Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\FluxController::index' => '?',
            'App\\Controller\\LabelController::generateWordFile' => '?',
            'App\\Controller\\LabelController::index' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::es' => '?',
            'App\\Controller\\ProductController::generateBarcode' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::searchByBarcode' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProviderController::delete' => '?',
            'App\\Controller\\ProviderController::edit' => '?',
            'App\\Controller\\ProviderController::index' => '?',
            'App\\Controller\\ProviderController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\FluxController:index' => '?',
            'App\\Controller\\LabelController:generateWordFile' => '?',
            'App\\Controller\\LabelController:index' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:es' => '?',
            'App\\Controller\\ProductController:generateBarcode' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:searchByBarcode' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProviderController:delete' => '?',
            'App\\Controller\\ProviderController:edit' => '?',
            'App\\Controller\\ProviderController:index' => '?',
            'App\\Controller\\ProviderController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
